
package cr.ac.una.tarea.soap;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ModuleJobsCompetences", targetNamespace = "http://controller.tareaws.una.ac.cr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ModuleJobsCompetences {


    /**
     * 
     * @param id
     * @return
     *     returns cr.ac.una.tarea.soap.JobsCompetencesDto
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getJobCompetenceId", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetJobCompetenceId")
    @ResponseWrapper(localName = "getJobCompetenceIdResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetJobCompetenceIdResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleJobsCompetences/getJobCompetenceIdRequest", output = "http://controller.tareaws.una.ac.cr/ModuleJobsCompetences/getJobCompetenceIdResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://controller.tareaws.una.ac.cr/ModuleJobsCompetences/getJobCompetenceId/Fault/IOException")
    })
    public JobsCompetencesDto getJobCompetenceId(
        @WebParam(name = "id", targetNamespace = "")
        Integer id)
        throws IOException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<cr.ac.una.tarea.soap.JobsCompetencesDto>
     * @throws IOException_Exception
     */
    @WebMethod(operationName = "GetJobCompetences")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetJobCompetences", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetJobCompetences")
    @ResponseWrapper(localName = "GetJobCompetencesResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetJobCompetencesResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleJobsCompetences/GetJobCompetencesRequest", output = "http://controller.tareaws.una.ac.cr/ModuleJobsCompetences/GetJobCompetencesResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://controller.tareaws.una.ac.cr/ModuleJobsCompetences/GetJobCompetences/Fault/IOException")
    })
    public List<JobsCompetencesDto> getJobCompetences()
        throws IOException_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "Delete")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Delete", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.Delete")
    @ResponseWrapper(localName = "DeleteResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.DeleteResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleJobsCompetences/DeleteRequest", output = "http://controller.tareaws.una.ac.cr/ModuleJobsCompetences/DeleteResponse")
    public Boolean delete(
        @WebParam(name = "Id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param idJobC
     * @return
     *     returns cr.ac.una.tarea.soap.JobsCompetencesDto
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getJobCompetenceIDJob", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetJobCompetenceIDJob")
    @ResponseWrapper(localName = "getJobCompetenceIDJobResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetJobCompetenceIDJobResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleJobsCompetences/getJobCompetenceIDJobRequest", output = "http://controller.tareaws.una.ac.cr/ModuleJobsCompetences/getJobCompetenceIDJobResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://controller.tareaws.una.ac.cr/ModuleJobsCompetences/getJobCompetenceIDJob/Fault/IOException")
    })
    public JobsCompetencesDto getJobCompetenceIDJob(
        @WebParam(name = "idJobC", targetNamespace = "")
        Integer idJobC)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RegisterJobCompetences")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RegisterJobCompetences", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.RegisterJobCompetences")
    @ResponseWrapper(localName = "RegisterJobCompetencesResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.RegisterJobCompetencesResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleJobsCompetences/RegisterJobCompetencesRequest", output = "http://controller.tareaws.una.ac.cr/ModuleJobsCompetences/RegisterJobCompetencesResponse")
    public Boolean registerJobCompetences(
        @WebParam(name = "arg0", targetNamespace = "")
        JobsCompetencesDto arg0);

}
