
package cr.ac.una.tarea.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ModuleProcesoeva", targetNamespace = "http://controller.tareaws.una.ac.cr/", wsdlLocation = "http://localhost:8080/Competencias360Ws/ModuleProcesoeva?wsdl")
public class ModuleProcesoeva_Service
    extends Service
{

    private static final URL MODULEPROCESOEVA_WSDL_LOCATION;
    private static final WebServiceException MODULEPROCESOEVA_EXCEPTION;
    private static final QName MODULEPROCESOEVA_QNAME = new QName("http://controller.tareaws.una.ac.cr/", "ModuleProcesoeva");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Competencias360Ws/ModuleProcesoeva?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MODULEPROCESOEVA_WSDL_LOCATION = url;
        MODULEPROCESOEVA_EXCEPTION = e;
    }

    public ModuleProcesoeva_Service() {
        super(__getWsdlLocation(), MODULEPROCESOEVA_QNAME);
    }

    public ModuleProcesoeva_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MODULEPROCESOEVA_QNAME, features);
    }

    public ModuleProcesoeva_Service(URL wsdlLocation) {
        super(wsdlLocation, MODULEPROCESOEVA_QNAME);
    }

    public ModuleProcesoeva_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MODULEPROCESOEVA_QNAME, features);
    }

    public ModuleProcesoeva_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModuleProcesoeva_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ModuleProcesoeva
     */
    @WebEndpoint(name = "ModuleProcesoevaPort")
    public ModuleProcesoeva getModuleProcesoevaPort() {
        return super.getPort(new QName("http://controller.tareaws.una.ac.cr/", "ModuleProcesoevaPort"), ModuleProcesoeva.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModuleProcesoeva
     */
    @WebEndpoint(name = "ModuleProcesoevaPort")
    public ModuleProcesoeva getModuleProcesoevaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controller.tareaws.una.ac.cr/", "ModuleProcesoevaPort"), ModuleProcesoeva.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MODULEPROCESOEVA_EXCEPTION!= null) {
            throw MODULEPROCESOEVA_EXCEPTION;
        }
        return MODULEPROCESOEVA_WSDL_LOCATION;
    }

}
