
package cr.ac.una.tarea.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ModuleWorkers", targetNamespace = "http://controller.tareaws.una.ac.cr/", wsdlLocation = "http://localhost:8080/Competencias360Ws/ModuleWorkers?wsdl")
public class ModuleWorkers_Service
    extends Service
{

    private static final URL MODULEWORKERS_WSDL_LOCATION;
    private static final WebServiceException MODULEWORKERS_EXCEPTION;
    private static final QName MODULEWORKERS_QNAME = new QName("http://controller.tareaws.una.ac.cr/", "ModuleWorkers");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Competencias360Ws/ModuleWorkers?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MODULEWORKERS_WSDL_LOCATION = url;
        MODULEWORKERS_EXCEPTION = e;
    }

    public ModuleWorkers_Service() {
        super(__getWsdlLocation(), MODULEWORKERS_QNAME);
    }

    public ModuleWorkers_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MODULEWORKERS_QNAME, features);
    }

    public ModuleWorkers_Service(URL wsdlLocation) {
        super(wsdlLocation, MODULEWORKERS_QNAME);
    }

    public ModuleWorkers_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MODULEWORKERS_QNAME, features);
    }

    public ModuleWorkers_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModuleWorkers_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ModuleWorkers
     */
    @WebEndpoint(name = "ModuleWorkersPort")
    public ModuleWorkers getModuleWorkersPort() {
        return super.getPort(new QName("http://controller.tareaws.una.ac.cr/", "ModuleWorkersPort"), ModuleWorkers.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModuleWorkers
     */
    @WebEndpoint(name = "ModuleWorkersPort")
    public ModuleWorkers getModuleWorkersPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controller.tareaws.una.ac.cr/", "ModuleWorkersPort"), ModuleWorkers.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MODULEWORKERS_EXCEPTION!= null) {
            throw MODULEWORKERS_EXCEPTION;
        }
        return MODULEWORKERS_WSDL_LOCATION;
    }

}
