
package cr.ac.una.tarea.soap;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ModuleEvaluatorResult", targetNamespace = "http://controller.tareaws.una.ac.cr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ModuleEvaluatorResult {


    /**
     * 
     * @param nota
     * @return
     *     returns cr.ac.una.tarea.soap.EvaluatorResultDto
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEvaluatorResultByGrade", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetEvaluatorResultByGrade")
    @ResponseWrapper(localName = "getEvaluatorResultByGradeResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetEvaluatorResultByGradeResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleEvaluatorResult/getEvaluatorResultByGradeRequest", output = "http://controller.tareaws.una.ac.cr/ModuleEvaluatorResult/getEvaluatorResultByGradeResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://controller.tareaws.una.ac.cr/ModuleEvaluatorResult/getEvaluatorResultByGrade/Fault/IOException")
    })
    public EvaluatorResultDto getEvaluatorResultByGrade(
        @WebParam(name = "nota", targetNamespace = "")
        Integer nota)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RegisterEvaluatorResult")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RegisterEvaluatorResult", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.RegisterEvaluatorResult")
    @ResponseWrapper(localName = "RegisterEvaluatorResultResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.RegisterEvaluatorResultResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleEvaluatorResult/RegisterEvaluatorResultRequest", output = "http://controller.tareaws.una.ac.cr/ModuleEvaluatorResult/RegisterEvaluatorResultResponse")
    public Boolean registerEvaluatorResult(
        @WebParam(name = "arg0", targetNamespace = "")
        EvaluatorResultDto arg0);

    /**
     * 
     * @param id
     * @return
     *     returns cr.ac.una.tarea.soap.EvaluatorResultDto
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEvaluatorResultById", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetEvaluatorResultById")
    @ResponseWrapper(localName = "getEvaluatorResultByIdResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetEvaluatorResultByIdResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleEvaluatorResult/getEvaluatorResultByIdRequest", output = "http://controller.tareaws.una.ac.cr/ModuleEvaluatorResult/getEvaluatorResultByIdResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://controller.tareaws.una.ac.cr/ModuleEvaluatorResult/getEvaluatorResultById/Fault/IOException")
    })
    public EvaluatorResultDto getEvaluatorResultById(
        @WebParam(name = "id", targetNamespace = "")
        Integer id)
        throws IOException_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "Delete")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Delete", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.Delete")
    @ResponseWrapper(localName = "DeleteResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.DeleteResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleEvaluatorResult/DeleteRequest", output = "http://controller.tareaws.una.ac.cr/ModuleEvaluatorResult/DeleteResponse")
    public Boolean delete(
        @WebParam(name = "Id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @return
     *     returns java.util.List<cr.ac.una.tarea.soap.EvaluatorResultDto>
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEvaluatorResult", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetEvaluatorResult")
    @ResponseWrapper(localName = "getEvaluatorResultResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetEvaluatorResultResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleEvaluatorResult/getEvaluatorResultRequest", output = "http://controller.tareaws.una.ac.cr/ModuleEvaluatorResult/getEvaluatorResultResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://controller.tareaws.una.ac.cr/ModuleEvaluatorResult/getEvaluatorResult/Fault/IOException")
    })
    public List<EvaluatorResultDto> getEvaluatorResult()
        throws IOException_Exception
    ;

}
