
package cr.ac.una.tarea.soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ModuleEvaluated", targetNamespace = "http://controller.tareaws.una.ac.cr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ModuleEvaluated {


    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "Delete")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Delete", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.Delete")
    @ResponseWrapper(localName = "DeleteResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.DeleteResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleEvaluated/DeleteRequest", output = "http://controller.tareaws.una.ac.cr/ModuleEvaluated/DeleteResponse")
    public Boolean delete(
        @WebParam(name = "Id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param id
     * @return
     *     returns cr.ac.una.tarea.soap.EvaluatedDto
     * @throws IOException_Exception
     */
    @WebMethod(operationName = "GetEvaluatedById")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetEvaluatedById", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetEvaluatedById")
    @ResponseWrapper(localName = "GetEvaluatedByIdResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetEvaluatedByIdResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleEvaluated/GetEvaluatedByIdRequest", output = "http://controller.tareaws.una.ac.cr/ModuleEvaluated/GetEvaluatedByIdResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://controller.tareaws.una.ac.cr/ModuleEvaluated/GetEvaluatedById/Fault/IOException")
    })
    public EvaluatedDto getEvaluatedById(
        @WebParam(name = "id", targetNamespace = "")
        Integer id)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RegisterEvaluated")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RegisterEvaluated", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.RegisterEvaluated")
    @ResponseWrapper(localName = "RegisterEvaluatedResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.RegisterEvaluatedResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleEvaluated/RegisterEvaluatedRequest", output = "http://controller.tareaws.una.ac.cr/ModuleEvaluated/RegisterEvaluatedResponse")
    public Boolean registerEvaluated(
        @WebParam(name = "arg0", targetNamespace = "")
        EvaluatedDto arg0);

}
