
package cr.ac.una.tarea.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ModuleCompetences", targetNamespace = "http://controller.tareaws.una.ac.cr/", wsdlLocation = "http://localhost:8080/Competencias360Ws/ModuleCompetences?wsdl")
public class ModuleCompetences_Service
    extends Service
{

    private static final URL MODULECOMPETENCES_WSDL_LOCATION;
    private static final WebServiceException MODULECOMPETENCES_EXCEPTION;
    private static final QName MODULECOMPETENCES_QNAME = new QName("http://controller.tareaws.una.ac.cr/", "ModuleCompetences");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Competencias360Ws/ModuleCompetences?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MODULECOMPETENCES_WSDL_LOCATION = url;
        MODULECOMPETENCES_EXCEPTION = e;
    }

    public ModuleCompetences_Service() {
        super(__getWsdlLocation(), MODULECOMPETENCES_QNAME);
    }

    public ModuleCompetences_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MODULECOMPETENCES_QNAME, features);
    }

    public ModuleCompetences_Service(URL wsdlLocation) {
        super(wsdlLocation, MODULECOMPETENCES_QNAME);
    }

    public ModuleCompetences_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MODULECOMPETENCES_QNAME, features);
    }

    public ModuleCompetences_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModuleCompetences_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ModuleCompetences
     */
    @WebEndpoint(name = "ModuleCompetencesPort")
    public ModuleCompetences getModuleCompetencesPort() {
        return super.getPort(new QName("http://controller.tareaws.una.ac.cr/", "ModuleCompetencesPort"), ModuleCompetences.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModuleCompetences
     */
    @WebEndpoint(name = "ModuleCompetencesPort")
    public ModuleCompetences getModuleCompetencesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controller.tareaws.una.ac.cr/", "ModuleCompetencesPort"), ModuleCompetences.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MODULECOMPETENCES_EXCEPTION!= null) {
            throw MODULECOMPETENCES_EXCEPTION;
        }
        return MODULECOMPETENCES_WSDL_LOCATION;
    }

}
