
package cr.ac.una.tarea.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ModuleEvaluators", targetNamespace = "http://controller.tareaws.una.ac.cr/", wsdlLocation = "http://localhost:8080/Competencias360Ws/ModuleEvaluators?wsdl")
public class ModuleEvaluators_Service
    extends Service
{

    private static final URL MODULEEVALUATORS_WSDL_LOCATION;
    private static final WebServiceException MODULEEVALUATORS_EXCEPTION;
    private static final QName MODULEEVALUATORS_QNAME = new QName("http://controller.tareaws.una.ac.cr/", "ModuleEvaluators");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Competencias360Ws/ModuleEvaluators?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MODULEEVALUATORS_WSDL_LOCATION = url;
        MODULEEVALUATORS_EXCEPTION = e;
    }

    public ModuleEvaluators_Service() {
        super(__getWsdlLocation(), MODULEEVALUATORS_QNAME);
    }

    public ModuleEvaluators_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MODULEEVALUATORS_QNAME, features);
    }

    public ModuleEvaluators_Service(URL wsdlLocation) {
        super(wsdlLocation, MODULEEVALUATORS_QNAME);
    }

    public ModuleEvaluators_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MODULEEVALUATORS_QNAME, features);
    }

    public ModuleEvaluators_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModuleEvaluators_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ModuleEvaluators
     */
    @WebEndpoint(name = "ModuleEvaluatorsPort")
    public ModuleEvaluators getModuleEvaluatorsPort() {
        return super.getPort(new QName("http://controller.tareaws.una.ac.cr/", "ModuleEvaluatorsPort"), ModuleEvaluators.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModuleEvaluators
     */
    @WebEndpoint(name = "ModuleEvaluatorsPort")
    public ModuleEvaluators getModuleEvaluatorsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controller.tareaws.una.ac.cr/", "ModuleEvaluatorsPort"), ModuleEvaluators.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MODULEEVALUATORS_EXCEPTION!= null) {
            throw MODULEEVALUATORS_EXCEPTION;
        }
        return MODULEEVALUATORS_WSDL_LOCATION;
    }

}
