
package cr.ac.una.tarea.soap;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ModuleCharacteristic", targetNamespace = "http://controller.tareaws.una.ac.cr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ModuleCharacteristic {


    /**
     * 
     * @return
     *     returns java.util.List<cr.ac.una.tarea.soap.CharacteristicDto>
     * @throws IOException_Exception
     */
    @WebMethod(operationName = "GetCharacteristics")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetCharacteristics", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetCharacteristics")
    @ResponseWrapper(localName = "GetCharacteristicsResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetCharacteristicsResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleCharacteristic/GetCharacteristicsRequest", output = "http://controller.tareaws.una.ac.cr/ModuleCharacteristic/GetCharacteristicsResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://controller.tareaws.una.ac.cr/ModuleCharacteristic/GetCharacteristics/Fault/IOException")
    })
    public List<CharacteristicDto> getCharacteristics()
        throws IOException_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns cr.ac.una.tarea.soap.CharacteristicDto
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getByCcId", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetByCcId")
    @ResponseWrapper(localName = "getByCcIdResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetByCcIdResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleCharacteristic/getByCcIdRequest", output = "http://controller.tareaws.una.ac.cr/ModuleCharacteristic/getByCcIdResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://controller.tareaws.una.ac.cr/ModuleCharacteristic/getByCcId/Fault/IOException")
    })
    public CharacteristicDto getByCcId(
        @WebParam(name = "id", targetNamespace = "")
        Integer id)
        throws IOException_Exception
    ;

    /**
     * 
     * @param name
     * @return
     *     returns cr.ac.una.tarea.soap.CharacteristicDto
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByCcName", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.FindByCcName")
    @ResponseWrapper(localName = "findByCcNameResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.FindByCcNameResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleCharacteristic/findByCcNameRequest", output = "http://controller.tareaws.una.ac.cr/ModuleCharacteristic/findByCcNameResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://controller.tareaws.una.ac.cr/ModuleCharacteristic/findByCcName/Fault/IOException")
    })
    public CharacteristicDto findByCcName(
        @WebParam(name = "name", targetNamespace = "")
        String name)
        throws IOException_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "Delete")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Delete", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.Delete")
    @ResponseWrapper(localName = "DeleteResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.DeleteResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleCharacteristic/DeleteRequest", output = "http://controller.tareaws.una.ac.cr/ModuleCharacteristic/DeleteResponse")
    public Boolean delete(
        @WebParam(name = "Id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RegisterCharacteristic")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RegisterCharacteristic", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.RegisterCharacteristic")
    @ResponseWrapper(localName = "RegisterCharacteristicResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.RegisterCharacteristicResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleCharacteristic/RegisterCharacteristicRequest", output = "http://controller.tareaws.una.ac.cr/ModuleCharacteristic/RegisterCharacteristicResponse")
    public Boolean registerCharacteristic(
        @WebParam(name = "arg0", targetNamespace = "")
        CharacteristicDto arg0);

}
