
package cr.ac.una.tarea.soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ModuleResult", targetNamespace = "http://controller.tareaws.una.ac.cr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ModuleResult {


    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "Delete")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Delete", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.Delete")
    @ResponseWrapper(localName = "DeleteResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.DeleteResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleResult/DeleteRequest", output = "http://controller.tareaws.una.ac.cr/ModuleResult/DeleteResponse")
    public Boolean delete(
        @WebParam(name = "Id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param id
     * @return
     *     returns cr.ac.una.tarea.soap.ResultDto
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getResultById", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetResultById")
    @ResponseWrapper(localName = "getResultByIdResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetResultByIdResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleResult/getResultByIdRequest", output = "http://controller.tareaws.una.ac.cr/ModuleResult/getResultByIdResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://controller.tareaws.una.ac.cr/ModuleResult/getResultById/Fault/IOException")
    })
    public ResultDto getResultById(
        @WebParam(name = "id", targetNamespace = "")
        Integer id)
        throws IOException_Exception
    ;

    /**
     * 
     * @param nota
     * @return
     *     returns cr.ac.una.tarea.soap.ResultDto
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getResultByGrade", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetResultByGrade")
    @ResponseWrapper(localName = "getResultByGradeResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetResultByGradeResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleResult/getResultByGradeRequest", output = "http://controller.tareaws.una.ac.cr/ModuleResult/getResultByGradeResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://controller.tareaws.una.ac.cr/ModuleResult/getResultByGrade/Fault/IOException")
    })
    public ResultDto getResultByGrade(
        @WebParam(name = "nota", targetNamespace = "")
        Integer nota)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RegisterResult")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RegisterResult", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.RegisterResult")
    @ResponseWrapper(localName = "RegisterResultResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.RegisterResultResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleResult/RegisterResultRequest", output = "http://controller.tareaws.una.ac.cr/ModuleResult/RegisterResultResponse")
    public Boolean registerResult(
        @WebParam(name = "arg0", targetNamespace = "")
        ResultDto arg0);

}
