
package cr.ac.una.tarea.soap;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ModuleEvaluated", targetNamespace = "http://controller.tareaws.una.ac.cr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ModuleEvaluated {


    /**
     * 
     * @param aplicacion
     * @param dto
     * @param finalizado
     * @param inicio
     */
    @WebMethod
    @RequestWrapper(localName = "setDate", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.SetDate")
    @ResponseWrapper(localName = "setDateResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.SetDateResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleEvaluated/setDateRequest", output = "http://controller.tareaws.una.ac.cr/ModuleEvaluated/setDateResponse")
    public void setDate(
        @WebParam(name = "dto", targetNamespace = "")
        Procesoeva dto,
        @WebParam(name = "Aplicacion", targetNamespace = "")
        String aplicacion,
        @WebParam(name = "finalizado", targetNamespace = "")
        String finalizado,
        @WebParam(name = "inicio", targetNamespace = "")
        String inicio);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "Delete")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Delete", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.Delete")
    @ResponseWrapper(localName = "DeleteResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.DeleteResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleEvaluated/DeleteRequest", output = "http://controller.tareaws.una.ac.cr/ModuleEvaluated/DeleteResponse")
    public Boolean delete(
        @WebParam(name = "Id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RegisterEvaluated")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RegisterEvaluated", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.RegisterEvaluated")
    @ResponseWrapper(localName = "RegisterEvaluatedResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.RegisterEvaluatedResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleEvaluated/RegisterEvaluatedRequest", output = "http://controller.tareaws.una.ac.cr/ModuleEvaluated/RegisterEvaluatedResponse")
    public Boolean registerEvaluated(
        @WebParam(name = "arg0", targetNamespace = "")
        EvaluatedDto arg0);

    /**
     * 
     * @param id
     * @return
     *     returns cr.ac.una.tarea.soap.EvaluatedDto
     * @throws IOException_Exception
     */
    @WebMethod(operationName = "GetEvaluatedById")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetEvaluatedById", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetEvaluatedById")
    @ResponseWrapper(localName = "GetEvaluatedByIdResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetEvaluatedByIdResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleEvaluated/GetEvaluatedByIdRequest", output = "http://controller.tareaws.una.ac.cr/ModuleEvaluated/GetEvaluatedByIdResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://controller.tareaws.una.ac.cr/ModuleEvaluated/GetEvaluatedById/Fault/IOException")
    })
    public EvaluatedDto getEvaluatedById(
        @WebParam(name = "id", targetNamespace = "")
        Integer id)
        throws IOException_Exception
    ;

    /**
     * 
     * @param proceso
     * @param worker
     * @return
     *     returns cr.ac.una.tarea.soap.EvaluatedDto
     * @throws IOException_Exception
     */
    @WebMethod(operationName = "GetEvaluatedByInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetEvaluatedByInfo", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetEvaluatedByInfo")
    @ResponseWrapper(localName = "GetEvaluatedByInfoResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetEvaluatedByInfoResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleEvaluated/GetEvaluatedByInfoRequest", output = "http://controller.tareaws.una.ac.cr/ModuleEvaluated/GetEvaluatedByInfoResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://controller.tareaws.una.ac.cr/ModuleEvaluated/GetEvaluatedByInfo/Fault/IOException")
    })
    public EvaluatedDto getEvaluatedByInfo(
        @WebParam(name = "worker", targetNamespace = "")
        Integer worker,
        @WebParam(name = "proceso", targetNamespace = "")
        Integer proceso)
        throws IOException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<cr.ac.una.tarea.soap.EvaluatedDto>
     * @throws IOException_Exception
     */
    @WebMethod(operationName = "GetEvaluateds")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetEvaluateds", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetEvaluateds")
    @ResponseWrapper(localName = "GetEvaluatedsResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetEvaluatedsResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleEvaluated/GetEvaluatedsRequest", output = "http://controller.tareaws.una.ac.cr/ModuleEvaluated/GetEvaluatedsResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://controller.tareaws.una.ac.cr/ModuleEvaluated/GetEvaluateds/Fault/IOException")
    })
    public List<EvaluatedDto> getEvaluateds()
        throws IOException_Exception
    ;

}
