
package cr.ac.una.tarea.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ModuleJobsCompetences", targetNamespace = "http://controller.tareaws.una.ac.cr/", wsdlLocation = "http://localhost:8080/Competencias360Ws/ModuleJobsCompetences?wsdl")
public class ModuleJobsCompetences_Service
    extends Service
{

    private static final URL MODULEJOBSCOMPETENCES_WSDL_LOCATION;
    private static final WebServiceException MODULEJOBSCOMPETENCES_EXCEPTION;
    private static final QName MODULEJOBSCOMPETENCES_QNAME = new QName("http://controller.tareaws.una.ac.cr/", "ModuleJobsCompetences");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Competencias360Ws/ModuleJobsCompetences?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MODULEJOBSCOMPETENCES_WSDL_LOCATION = url;
        MODULEJOBSCOMPETENCES_EXCEPTION = e;
    }

    public ModuleJobsCompetences_Service() {
        super(__getWsdlLocation(), MODULEJOBSCOMPETENCES_QNAME);
    }

    public ModuleJobsCompetences_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MODULEJOBSCOMPETENCES_QNAME, features);
    }

    public ModuleJobsCompetences_Service(URL wsdlLocation) {
        super(wsdlLocation, MODULEJOBSCOMPETENCES_QNAME);
    }

    public ModuleJobsCompetences_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MODULEJOBSCOMPETENCES_QNAME, features);
    }

    public ModuleJobsCompetences_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModuleJobsCompetences_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ModuleJobsCompetences
     */
    @WebEndpoint(name = "ModuleJobsCompetencesPort")
    public ModuleJobsCompetences getModuleJobsCompetencesPort() {
        return super.getPort(new QName("http://controller.tareaws.una.ac.cr/", "ModuleJobsCompetencesPort"), ModuleJobsCompetences.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModuleJobsCompetences
     */
    @WebEndpoint(name = "ModuleJobsCompetencesPort")
    public ModuleJobsCompetences getModuleJobsCompetencesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controller.tareaws.una.ac.cr/", "ModuleJobsCompetencesPort"), ModuleJobsCompetences.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MODULEJOBSCOMPETENCES_EXCEPTION!= null) {
            throw MODULEJOBSCOMPETENCES_EXCEPTION;
        }
        return MODULEJOBSCOMPETENCES_WSDL_LOCATION;
    }

}
