
package cr.ac.una.tarea.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ModuleComInformation", targetNamespace = "http://controller.tareaws.una.ac.cr/", wsdlLocation = "http://localhost:8080/Competencias360Ws/ModuleComInformation?wsdl")
public class ModuleComInformation_Service
    extends Service
{

    private static final URL MODULECOMINFORMATION_WSDL_LOCATION;
    private static final WebServiceException MODULECOMINFORMATION_EXCEPTION;
    private static final QName MODULECOMINFORMATION_QNAME = new QName("http://controller.tareaws.una.ac.cr/", "ModuleComInformation");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Competencias360Ws/ModuleComInformation?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MODULECOMINFORMATION_WSDL_LOCATION = url;
        MODULECOMINFORMATION_EXCEPTION = e;
    }

    public ModuleComInformation_Service() {
        super(__getWsdlLocation(), MODULECOMINFORMATION_QNAME);
    }

    public ModuleComInformation_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MODULECOMINFORMATION_QNAME, features);
    }

    public ModuleComInformation_Service(URL wsdlLocation) {
        super(wsdlLocation, MODULECOMINFORMATION_QNAME);
    }

    public ModuleComInformation_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MODULECOMINFORMATION_QNAME, features);
    }

    public ModuleComInformation_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModuleComInformation_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ModuleComInformation
     */
    @WebEndpoint(name = "ModuleComInformationPort")
    public ModuleComInformation getModuleComInformationPort() {
        return super.getPort(new QName("http://controller.tareaws.una.ac.cr/", "ModuleComInformationPort"), ModuleComInformation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModuleComInformation
     */
    @WebEndpoint(name = "ModuleComInformationPort")
    public ModuleComInformation getModuleComInformationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controller.tareaws.una.ac.cr/", "ModuleComInformationPort"), ModuleComInformation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MODULECOMINFORMATION_EXCEPTION!= null) {
            throw MODULECOMINFORMATION_EXCEPTION;
        }
        return MODULECOMINFORMATION_WSDL_LOCATION;
    }

}
