
package cr.ac.una.tarea.soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ModuleProcesoeva", targetNamespace = "http://controller.tareaws.una.ac.cr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ModuleProcesoeva {


    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "Delete")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Delete", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.Delete")
    @ResponseWrapper(localName = "DeleteResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.DeleteResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleProcesoeva/DeleteRequest", output = "http://controller.tareaws.una.ac.cr/ModuleProcesoeva/DeleteResponse")
    public Boolean delete(
        @WebParam(name = "Id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RegisterProcesova")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RegisterProcesova", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.RegisterProcesova")
    @ResponseWrapper(localName = "RegisterProcesovaResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.RegisterProcesovaResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleProcesoeva/RegisterProcesovaRequest", output = "http://controller.tareaws.una.ac.cr/ModuleProcesoeva/RegisterProcesovaResponse")
    public Boolean registerProcesova(
        @WebParam(name = "arg0", targetNamespace = "")
        ProcesoevaDto arg0);

    /**
     * 
     * @param name
     * @return
     *     returns cr.ac.una.tarea.soap.ProcesoevaDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProcesova", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetProcesova")
    @ResponseWrapper(localName = "getProcesovaResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetProcesovaResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleProcesoeva/getProcesovaRequest", output = "http://controller.tareaws.una.ac.cr/ModuleProcesoeva/getProcesovaResponse")
    public ProcesoevaDto getProcesova(
        @WebParam(name = "Name", targetNamespace = "")
        String name);

}
