
package cr.ac.una.tarea.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ModuleEvaluatorResult", targetNamespace = "http://controller.tareaws.una.ac.cr/", wsdlLocation = "http://localhost:8080/Competencias360Ws/ModuleEvaluatorResult?wsdl")
public class ModuleEvaluatorResult_Service
    extends Service
{

    private static final URL MODULEEVALUATORRESULT_WSDL_LOCATION;
    private static final WebServiceException MODULEEVALUATORRESULT_EXCEPTION;
    private static final QName MODULEEVALUATORRESULT_QNAME = new QName("http://controller.tareaws.una.ac.cr/", "ModuleEvaluatorResult");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Competencias360Ws/ModuleEvaluatorResult?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MODULEEVALUATORRESULT_WSDL_LOCATION = url;
        MODULEEVALUATORRESULT_EXCEPTION = e;
    }

    public ModuleEvaluatorResult_Service() {
        super(__getWsdlLocation(), MODULEEVALUATORRESULT_QNAME);
    }

    public ModuleEvaluatorResult_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MODULEEVALUATORRESULT_QNAME, features);
    }

    public ModuleEvaluatorResult_Service(URL wsdlLocation) {
        super(wsdlLocation, MODULEEVALUATORRESULT_QNAME);
    }

    public ModuleEvaluatorResult_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MODULEEVALUATORRESULT_QNAME, features);
    }

    public ModuleEvaluatorResult_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModuleEvaluatorResult_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ModuleEvaluatorResult
     */
    @WebEndpoint(name = "ModuleEvaluatorResultPort")
    public ModuleEvaluatorResult getModuleEvaluatorResultPort() {
        return super.getPort(new QName("http://controller.tareaws.una.ac.cr/", "ModuleEvaluatorResultPort"), ModuleEvaluatorResult.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModuleEvaluatorResult
     */
    @WebEndpoint(name = "ModuleEvaluatorResultPort")
    public ModuleEvaluatorResult getModuleEvaluatorResultPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controller.tareaws.una.ac.cr/", "ModuleEvaluatorResultPort"), ModuleEvaluatorResult.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MODULEEVALUATORRESULT_EXCEPTION!= null) {
            throw MODULEEVALUATORRESULT_EXCEPTION;
        }
        return MODULEEVALUATORRESULT_WSDL_LOCATION;
    }

}
