
package cr.ac.una.tarea.soap;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ModuleCompetences", targetNamespace = "http://controller.tareaws.una.ac.cr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ModuleCompetences {


    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "Delete")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Delete", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.Delete")
    @ResponseWrapper(localName = "DeleteResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.DeleteResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleCompetences/DeleteRequest", output = "http://controller.tareaws.una.ac.cr/ModuleCompetences/DeleteResponse")
    public Boolean delete(
        @WebParam(name = "Id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param name
     * @return
     *     returns cr.ac.una.tarea.soap.CompetencesDto
     * @throws IOException_Exception
     */
    @WebMethod(operationName = "GetCompetence")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetCompetence", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetCompetence")
    @ResponseWrapper(localName = "GetCompetenceResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetCompetenceResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleCompetences/GetCompetenceRequest", output = "http://controller.tareaws.una.ac.cr/ModuleCompetences/GetCompetenceResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://controller.tareaws.una.ac.cr/ModuleCompetences/GetCompetence/Fault/IOException")
    })
    public CompetencesDto getCompetence(
        @WebParam(name = "Name", targetNamespace = "")
        String name)
        throws IOException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<cr.ac.una.tarea.soap.CompetencesDto>
     * @throws IOException_Exception
     */
    @WebMethod(operationName = "GetCompetences")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetCompetences", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetCompetences")
    @ResponseWrapper(localName = "GetCompetencesResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.GetCompetencesResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleCompetences/GetCompetencesRequest", output = "http://controller.tareaws.una.ac.cr/ModuleCompetences/GetCompetencesResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://controller.tareaws.una.ac.cr/ModuleCompetences/GetCompetences/Fault/IOException")
    })
    public List<CompetencesDto> getCompetences()
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RegisterCompetences")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RegisterCompetences", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.RegisterCompetences")
    @ResponseWrapper(localName = "RegisterCompetencesResponse", targetNamespace = "http://controller.tareaws.una.ac.cr/", className = "cr.ac.una.tarea.soap.RegisterCompetencesResponse")
    @Action(input = "http://controller.tareaws.una.ac.cr/ModuleCompetences/RegisterCompetencesRequest", output = "http://controller.tareaws.una.ac.cr/ModuleCompetences/RegisterCompetencesResponse")
    public Boolean registerCompetences(
        @WebParam(name = "arg0", targetNamespace = "")
        CompetencesDto arg0);

}
